### ISSUE TITLE
Decouple Arm Swinging from all Checks?

### ISSUE THREAD

**Issue by xEvoGx** [ElectricNightOwl/ArmSwinger#35]
Now that I've had more time to continue working, and of course talking to you about the raycasting I have what I hope isn't asking too much!

What it be possible to have a pure ArmSwinger that is nothing more than simply the movement derived from swinging your arms? Keep the curves and inertia (this is a must!) but completely truncate all the checks, raycasting and all other protections. Essentially (and within the package mind you) you can have **Full Arm Swinger** script, which is what you have now, and an **Arm Swinger Raw/Lite/Pure** script that is nothing more than the movement. 

Maybe? Pretty please?? :smile: 

Thanks so much kJack!

**Comment by kjack9** [comment]
Does turning off all the Prevention Methods and setting playAreaHeightAdjustmentPaused to true accomplish this for you?

**Comment by xEvoGx** [comment]
Actually yes your new script seems perfect! If I'm not mistaken, this now more or less achieves what I was looking for in a _lite_ version, right?

Very cool man thank you for your time!

**Comment by kjack9** [comment]
If other folks ask for something like ArmSwinger without the prevention methods, I may split it into two or maybe just implement an easy toggle for it.  For now, I think the options are there, even if they are a bit non-intuitive.

Closing for now.

**Comment by xEvoGx** [comment]
Agreed and thank you again kjack!
