### ISSUE TITLE
Anyway to disable some colliders ?

### ISSUE THREAD

**Issue by ymarzack** [ElectricNightOwl/ArmSwinger#48]
I have an avatar (enemy) with a 10 meters sphere collider set on it (for simulating sighting)
But unfortunately, this prevent the player to get close to the avatar, as ArmSwinger prevent to walk when hitting the sphere collider as it was a wall.

I have disabled all prevent settings but it is always the same behavior.

Is there anyway to make this sphere collider "transparent" for ArmSwinger" ? (by settings / layers or by change the code ?)

Many thanks

**Comment by kjack9** [comment]
Absolutely there is.

https://github.com/ElectricNightOwl/ArmSwinger#prevent-wall-clip-settings

Check out the "Prevent Wall Clip - Layer Mask" settings.  That should let you specify which layers to collide with.

If you still have the issue, feel free to email me directly at github@electricnightowl.com.

**Comment by ymarzack** [comment]
Many thanks for your answer !

Your script is very awesome. great works.

Best
