### ISSUE TITLE
Falling animation

### ISSUE THREAD

**Issue by lucasdoppelt** [ElectricNightOwl/ArmSwinger#49]
Hi,

First, thanks for this very nice script ! It is very well done !

I would like to make my character fall when he goes off cliff. Right now when the player fall from a platform he is instantly teleported on the ground. I would like to have the natural falling animation. How can it be acheived ?? 

Thanks a lot,

Lucas

**Comment by kjack9** [comment]
Hi Lucas,

ArmSwinger uses it's own "physics" calculations, and does not use a rigidbody that CAN fall.  If you disable falling prevention, the camera will continue to snap to the ground, as you noticed.

If you're looking for something that will allow jumping, falling, etc might I recommend MoveInPlace (which is a part of VRTK)?  It accomplishes something similar to ArmSwinger using a rigidbody with physics applied.

Sorry, but this feature is not possible with the way ArmSwinger is currently designed.

-KJack
