### ISSUE TITLE
Is it Compatible With Newton VR?

### ISSUE THREAD

**Issue by Oyshoboy** [ElectricNightOwl/ArmSwinger#51]
Hi ! want to buy this asset and use it with Newton VR.

So question : Is it Compatible With Newton VR?

**Comment by kjack9** [comment]
Hi there,

I have not personally tested ArmSwinger with Newton VR - sorry!  You can always try the open source version from GitHub first and then decide if you'd like to purchase via the Unity Asset Store.

Good luck!

-KJack

**Comment by Oyshoboy** [comment]
Nope, it's isn't compatible :(
And whats the difference between open sourced and Unity Asset Store Version?

**Comment by kjack9** [comment]
No difference in functionality.  The Unity Asset Store version includes a demo scene that is not open sourced.  The two versions give you the option to support me if you want to, or to use ArmSwinger freely - your call!
