### ISSUE TITLE
Is this compatible with oculus?

### ISSUE THREAD

**Issue by spaez18** [ElectricNightOwl/ArmSwinger#53]
Hey! I've been looking how to make this kind of movement for the Oculus Rift and the nearest approach I've found is yours. I know you tested this on HTC Vive but I'd like to know if i can use this for Oculus or how can I start to develop the scripts for it. Thank you so much for any help you can give me.

Best regards.

**Comment by a-rts** [comment]
Anything that works with Vive uses OpenVR, which Oculus can also use. So any VR camera rig that provides the component SteamVR_ControllerManager should work, I guess.

**Comment by kjack9** [comment]
ArmSwinger was only tested using HTC Vive since that's the only VR headset I own.  I don't know what the side effects would be of using it with a Rift.
